/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "requerimientos.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

paqueteInformacion *
consultarrequerimientos_1(void *argp, CLIENT *clnt)
{
	static paqueteInformacion clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, consultarRequerimientos,
		(xdrproc_t) xdr_void, (caddr_t) argp,
		(xdrproc_t) xdr_paqueteInformacion, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
